name: Build and Deploy to Google Cloud Run

on:
  push:
    tags:
      - 'v*'

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Build and Push Docker image
      run: |-
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/topics-audio-ml-infrastructure:${{ steps.get_version.outputs.VERSION }}

    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy topics-audio-ml-infrastructure --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/topics-audio-ml-infrastructure:${{ steps.get_version.outputs.VERSION }} --port 80 --platform managed

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }} # This token is provided by Actions
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          Changes in this Release
          - Docker image: `gcr.io/${{ secrets.GCP_PROJECT_ID }}/topics-audio-ml-infrastructure:${{ steps.get_version.outputs.VERSION }}`