name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker --quiet
          docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME .
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy topics-unmix \
            --source build \
            --region=us-central1
